server:
  port: 8000
spring:
  application:
    name: shorturl-service
  datasource:
    shorturl00:
      jdbc-url: jdbc:postgresql://192.168.0.103:5432/shorturldb
      username: postgres
      password: 12345678
      driver-class-name: org.postgresql.Driver
    shorturl01:
      jdbc-url: jdbc:postgresql://192.168.0.103:5433/shorturldb
      username: postgres
      password: 12345678
      driver-class-name: org.postgresql.Driver
    shorturl02:
      jdbc-url: jdbc:postgresql://192.168.0.103:5434/shorturldb
      username: postgres
      password: 12345678
      driver-class-name: org.postgresql.Driver
sys:
  config:
    domain: http://localhost:8000/
    sign: "ON"
